-- MySQL Script generated by MySQL Workbench
-- Mon Jul 29 02:31:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`directors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`directors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`directors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movies` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movies` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(20) NULL,
  `year_of_release` INT UNSIGNED NOT NULL,
  `poster_image` VARCHAR(45) NULL,
  `desc` TEXT(400) NULL,
  `Directors_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Movies_Directors1_idx` (`Directors_id` ASC),
  CONSTRAINT `fk_Movies_Directors1`
    FOREIGN KEY (`Directors_id`)
    REFERENCES `mydb`.`directors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genres` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genres` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`genre_movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`genre_movie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`genre_movie` (
  `movie_id` INT UNSIGNED NOT NULL,
  `genre_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`movie_id`, `genre_id`),
  INDEX `fk_Movies_has_Genres_Genres1_idx` (`genre_id` ASC),
  INDEX `fk_Movies_has_Genres_Movies_idx` (`movie_id` ASC),
  CONSTRAINT `fk_Movies_has_Genres_Movies`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movies_has_Genres_Genres1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `mydb`.`genres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` TEXT(150) NULL,
  `date` VARCHAR(45) NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `movies_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comments_Users1_idx` (`users_id` ASC),
  INDEX `fk_Comments_Movies1_idx` (`movies_id` ASC),
  CONSTRAINT `fk_Comments_Users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comments_Movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `mydb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movie_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`movie_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`movie_user` (
  `user_id` INT UNSIGNED NOT NULL,
  `movie_id` INT UNSIGNED NOT NULL,
  `grades` INT UNSIGNED NULL,
  PRIMARY KEY (`user_id`, `movie_id`),
  INDEX `fk_Users_has_Movies_Movies1_idx` (`movie_id` ASC),
  INDEX `fk_Users_has_Movies_Users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_Users_has_Movies_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Movies_Movies1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `mydb`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
